name: Update Chocolatey packages if upstream update is available
on:
  schedule:
  - cron: "0 6/12 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-packages:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install dependencies
      run: choco install chocolatey-au
    - name: Setup Git commit author
      shell: pwsh
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - name: Update Chocolatey packages
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIST_API_KEY: ${{ secrets.GIST_API_KEY }}
        GIST_ID: ${{ vars.GIST_ID }}
        API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        .\update_all.ps1
